pipeline:
  name: integration_test
  workspace: test_workspace
  resume: true
robot:
  urdf_path: test.urdf
  base_frame: base
  ee_frame: ee
optimization:
  lr_pose: 0.001
  lr_scale: 0.005
  iterations: 50
  loss:
    type: soft_iou
    smooth: 1.0e-06
geometry:
  binding_method: adaptive_knn
  outlier_removal_std: 2.0
  adaptive_threshold_percentile: 95
gpu:
  max_memory_gb: 4.0
  enable_memory_monitoring: true
logging:
  level: INFO
  file: test.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
